### PR TITLE
Improved Portuguese locale

### PR DESCRIPTION
**Pull request by maiconkkl**

### CODE REVIEW

**Comment by HawaiiBeach** [comment]
Why does your translations begin with upper case still?

**Comment by maiconkkl** [comment]
> Why does your translations begin with upper case still?

fixed

**Comment by rex2630** [comment]
Fix fxmanifest

**Comment by maiconkkl** [comment]
> Fix fxmanifest

fixed

**Comment by rex2630** [comment]
Thanks :)

**Pull request merged**
